name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
    paths: 
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - "**.c"
      - ".github/workflows/build.yml"
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"
    paths: 
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - "**.c"
      - ".github/workflows/build.yml"

jobs:
  # build-windows-release:
  #   runs-on: windows-2022
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         clean: true
  #         submodules: recursive
  #         fetch-depth: 0

  #     - name: Generate build files
  #       run: |
  #         mkdir build
  #         cd build
  #         cmake -DCMAKE_BUILD_TYPE=Release .. -G "Visual Studio 17 2022" -A Win32
  #         cmake --build . --config Release

  #     - name: Create a folder for release
  #       shell: bash
  #       run: |
  #         mkdir dist
  #         cd dist
  #         mkdir components
  #         mkdir -p pawno/include
  #         mkdir -p qawno/include
  #         cd ..
  #         mv ./build/src/Release/pawnchalk.dll ./dist/components/pawnchalk.dll
  #         cp ./pawnchalk.inc ./dist/pawno/include/pawnchalk.inc
  #         cp ./pawnchalk.inc ./dist/qawno/include/pawnchalk.inc

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: pawnchalk-win
  #         path: dist/*

  build-linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Create artifact directory
        run: |
          mkdir -p artifact/plugins
          mkdir -p artifact/pawno/include
          mkdir -p artifact/qawno/include

      - name: Build
        run: |
          cd docker
          chmod +x ./build.sh
          chmod +x ./docker-entrypoint.sh
          ./build.sh

      - name: DEBUG
        run: |
          echo docker
          ls docker
          echo ======
          echo docker/build
          ls docker/build
          echo ======
          echo docker/build/lib
          ls docker/build/lib

      # - name: Move files
      #   run: |
      #     cp docker/build/pawnchalk.so artifact/plugins/pawnchalk.so
      #     cp pawnchalk.inc artifact/pawno/include/pawnchalk.inc
      #     cp pawnchalk.inc artifact/qawno/include/pawnchalk.inc

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pawnchalk-linux
      #     path: artifact/*